# Ultralytics YOLO 🚀，AGPL-3.0 许可协议
# 用于中等增强 COCO 训练的默认训练设置和超参数

task: detect # (str) YOLO 任务，例如 detect（检测）、segment（分割）、classify（分类）、pose（姿态估计）
mode: train # (str) YOLO 模式，例如 train（训练）、val（验证）、predict（预测）、export（导出）、track（追踪）、benchmark（基准测试）

# 训练设置 -------------------------------------------------------------------------------------------------------------
model: # (str, 可选) 模型文件路径，例如 yolov8n.pt、yolov8n.yaml
data: # (str, 可选) 数据文件路径，例如 coco128.yaml
epochs: 100 # (int) 训练的轮数
time: # (float, 可选) 训练的小时数，如果设置则优先生效，覆盖 epochs
patience: 10 # (int) 在训练早停前等待多少轮没有明显改进
batch: 16 # (int) 每批次图像数量（-1 表示自动批次）
imgsz: 640 # (int | list) 训练和验证的输入图像大小；预测和导出时可为列表 [w,h]
save: True # (bool) 是否保存训练检查点和预测结果
save_period: -1 # (int) 每训练多少轮保存一次检查点（<1 表示不启用）
val_period: 1 # (int) 每训练多少轮进行一次验证
cache: False # (bool) 使用缓存加载数据（True/ram、disk 或 False）
device: # (int | str | list, 可选) 指定运行设备，例如 cuda:0 或 [0,1,2,3] 或 cpu
workers: 8 # (int) 数据加载线程数（DDP 模式下为每个 RANK 的线程数）
project: # (str, 可选) 项目名称
name: # (str, 可选) 实验名称，结果保存到 'project/name' 目录
exist_ok: False # (bool) 是否允许覆盖已有实验
pretrained: True # (bool | str) 是否使用预训练模型（布尔值或提供模型路径）
optimizer: auto # (str) 使用的优化器，可选：[SGD, Adam, Adamax, AdamW, NAdam, RAdam, RMSProp, auto]
verbose: True # (bool) 是否打印详细日志
seed: 0 # (int) 用于可复现的随机种子
deterministic: True # (bool) 是否启用确定性模式
single_cls: False # (bool) 是否将多类别数据作为单类别训练
rect: True # (bool) 若为 train 模式则进行矩形训练，val 模式则为矩形验证
cos_lr: False # (bool) 是否使用余弦学习率调度器
close_mosaic: 10 # (int) 在最后多少轮禁用 mosaic 增强（0 表示不禁用）
resume: False # (bool) 是否从上次检查点恢复训练
amp: True # (bool) 是否启用自动混合精度 (AMP) 训练
fraction: 1.0 # (float) 使用训练集的比例（默认 1.0，即全部使用）
profile: False # (bool) 是否在训练期间分析 ONNX 和 TensorRT 的速度（用于日志）
freeze: None # (int | list, 可选) 冻结前 n 层，或指定冻结的层索引列表
multi_scale: True # (bool) 是否启用多尺度训练
albumentations:
  - CLAHE:
      p: 1.0


# 分割相关
overlap_mask: True # (bool) 训练期间 mask 是否允许重叠（仅 segment 训练）
mask_ratio: 4 # (int) mask 下采样比例（仅 segment 训练）

# 分类相关
dropout: 0.0 # (float) 使用 dropout 正则化（仅 classify 训练）

# 验证/测试设置 --------------------------------------------------------------------------------------------------------
val: True # (bool) 是否在训练期间验证/测试
split: val # (str) 用于验证的数据集划分，例如 'val'、'test' 或 'train'
save_json: True # (bool) 将结果保存为 JSON 文件
save_hybrid: False # (bool) 保存标签的混合版本（标签 + 额外预测）
conf: # (float, 可选) 检测时的目标置信度阈值（默认 predict 为 0.25，val 为 0.001）
iou: 0.7 # (float) 非极大值抑制（NMS）的 IoU 阈值
max_det: 300 # (int) 每张图像最多检测的目标数
half: False # (bool) 是否使用半精度 (FP16)
dnn: False # (bool) 是否使用 OpenCV DNN 进行 ONNX 推理
plots: True # (bool) 在训练/验证过程中保存图表和图像

# 预测设置 -------------------------------------------------------------------------------------------------------------
source: # (str, 可选) 图像或视频的源目录
vid_stride: 1 # (int) 视频帧率间隔
stream_buffer: False # (bool) 是否缓冲所有流帧（True）或只返回最新一帧（False）
visualize: False # (bool) 可视化模型特征
augment: False # (bool) 对预测源应用图像增强
agnostic_nms: False # (bool) 无类别的 NMS（即忽略类别信息）
classes: # (int | list[int], 可选) 根据类别过滤结果，例如 classes=0 或 classes=[0,2,3]
retina_masks: False # (bool) 使用高分辨率分割掩码
embed: # (list[int], 可选) 返回指定层的特征向量/嵌入

# 可视化设置 -----------------------------------------------------------------------------------------------------------
show: False # (bool) 若环境允许则显示预测图像和视频
save_frames: False # (bool) 保存每帧视频的预测结果
save_txt: False # (bool) 将结果保存为 .txt 文件
save_conf: False # (bool) 保存带置信度的预测结果
save_crop: False # (bool) 保存裁剪后的结果图像
show_labels: True # (bool) 显示预测标签，例如 'person'
show_conf: True # (bool) 显示预测置信度，例如 '0.99'
show_boxes: True # (bool) 显示预测框
line_width: # (int, 可选) 边框线宽，若为 None 则根据图像尺寸缩放

# 导出设置 -------------------------------------------------------------------------------------------------------------
format: torchscript # (str) 导出格式，可选格式见：https://docs.ultralytics.com/modes/export/#export-formats
keras: False # (bool) 是否导出为 Keras
optimize: False # (bool) TorchScript：是否为移动端优化
int8: False # (bool) CoreML/TF INT8 量化
dynamic: False # (bool) ONNX/TF/TensorRT：动态轴
simplify: False # (bool) ONNX：使用 `onnxslim` 简化模型
opset: # (int, 可选) ONNX：opset 版本
workspace: 4 # (int) TensorRT：工作空间大小（GB）
nms: False # (bool) CoreML：添加 NMS 操作

# 超参数设置 ------------------------------------------------------------------------------------------------------------
lr0: 0.01 # (float) 初始学习率（例如 SGD=1E-2，Adam=1E-3）
lrf: 0.01 # (float) 最终学习率（lr0 * lrf）
momentum: 0.937 # (float) SGD 动量 / Adam beta1
weight_decay: 0.0005 # (float) 优化器的权重衰减系数
warmup_epochs: 3.0 # (float) 预热轮数（可以为小数）
warmup_momentum: 0.8 # (float) 预热阶段初始动量
warmup_bias_lr: 0.1 # (float) 预热阶段初始偏置学习率
box: 7.5 # (float) 边框损失增益
cls: 0.5 # (float) 分类损失增益（按像素缩放）
dfl: 1.5 # (float) DFL 损失增益
pose: 12.0 # (float) 姿态损失增益
kobj: 1.0 # (float) 关键点目标损失增益
label_smoothing: 0.1 # (float) 标签平滑系数
nbs: 64 # (int) 名义批量大小
hsv_h: 0.015 # (float) 图像 HSV 色调增强（比例）
hsv_s: 0.7 # (float) 图像 HSV 饱和度增强（比例）
hsv_v: 0.4 # (float) 图像 HSV 明度增强（比例）
degrees: 0.0 # (float) 图像旋转（±度数）
translate: 0.1 # (float) 图像平移（±比例）
scale: 0.5 # (float) 图像缩放（±增益）
shear: 0.0 # (float) 图像剪切（±度数）
perspective: 0.0 # (float) 图像透视变化（±比例），范围 0-0.001
flipud: 0.0 # (float) 图像上下翻转（概率）
fliplr: 0.5 # (float) 图像左右翻转（概率）
bgr: 0.0 # (float) 图像通道 BGR（概率）
mosaic: 1.0 # (float) 图像 mosaic 增强（概率）
mixup: 0.0 # (float) 图像 mixup 增强（概率）
copy_paste: 0.0 # (float) 分割的 copy-paste 增强（概率）
auto_augment: randaugment # (str) 分类任务的自动增强策略（randaugment, autoaugment, augmix）
erasing: 0.4 # (float) 分类训练时的随机擦除概率（0-1）
crop_fraction: 1.0 # (float) 分类评估/推理时图像裁剪比例（0-1）

# 自定义配置文件 --------------------------------------------------------------------------------------------------------
cfg: # (str, 可选) 用于覆盖 defaults.yaml 的配置文件路径

# 跟踪器设置 ------------------------------------------------------------------------------------------------------------
tracker: botsort.yaml # (str) 跟踪器类型，可选：[botsort.yaml, bytetrack.yaml]
